version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qt: 5.14.2    
    releaseName: Visualized_Neural_Networks_qt5142_vs2017_x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x86
    qt: 5.14.2
    releaseName: Visualized_Neural_Networks_qt5142_vs2017_x86

before_build:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set msvc=msvc2017
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set vs=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
  - if "%platform%"=="x86" set QTDIR=C:\Qt\%qt%\%msvc%
  - if "%platform%"=="x64" set QTDIR=C:\Qt\%qt%\%msvc%_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - if "%platform%"=="x86" set vcvarsall=%vs%\vcvarsall.bat
  - if "%platform%"=="x64" set vcvarsall=%vs%\vcvarsall.bat
  - if "%platform%"=="x86" call "%vcvarsall%" x86
  - if "%platform%"=="x64" call "%vcvarsall%" x64

build_script:
  - qmake
  - nmake

after_build:
  - if "%APPVEYOR_REPO_TAG%"=="true" windeployqt bin\Visualized_Neural_Networks.exe --qmldir %QTDIR%\qml

artifacts:
  - path: bin
    name: $(releaseName)

deploy:
  provider: GitHub
  auth_token: $(GITHUB_OAUTH_TOKEN)
  description: 'Visualized Neural Networks Release'
  draft: false
  prerelease: false
  on:
      APPVEYOR_REPO_TAG: true