image: Visual Studio 2017

environment:
  matrix:
    - arch: x64
      compiler: msvc2017
    - arch: x86
      compiler: msvc2017
    - arch: x86
      compiler: msvc2015
    - arch: x64
      compiler: msvc2015

branches:
  only:
    - temp

platform:
  - x64

install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;


