version: 1.0.{build}

image: Visual Studio 2019

branches:
  only:
    - testCI

platform:
  - x64

install:
  - cmd: set QTDIR=C:\Qt\5.14.2\mingw73_64
  - cmd: set PATH=%PATH%,%QTDIR%\bin,C:MinGW\bin

build_script:
  - cmd: qmake code\src\Visualized_Neural_Networks.pro
  - cmd: mingw32-make
# -makefile -o code\build-Visualized_Neural_Networks-Desktop_Qt_5_14_2_MinGW_64_bit-Debug\Makefile 
